
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Extremetech
 */
public class Banco extends javax.swing.JFrame {

    //Asignamos a cuentas el ArrayList que vamos a leer
    ArrayList<Cuenta> cuentas = Utilidad.readFile("cuentas.txt");
    
    Cuenta actualCuenta;
    
    private void iniciarCuentas() {

        //Populamos ArrayList, usando un enhanced for loop
        for (Cuenta a : cuentas) {
            cuentaDropDown.addItem(a);
        }
    }

    /**
     * Creates new form Banco
     */
    public Banco() {
        initComponents();
        
        //Constructor
        iniciarCuentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clienteCampo = new javax.swing.JTextField();
        fechaCampo = new javax.swing.JTextField();
        balanceCampo = new javax.swing.JTextField();
        cuentaDropDown = new javax.swing.JComboBox<>();
        depositarBtn = new javax.swing.JButton();
        extraerBtn = new javax.swing.JButton();
        transferirBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Numero Cuenta:");

        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Cliente:");

        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Fecha Apertura:");

        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Saldo:");

        clienteCampo.setEditable(false);
        clienteCampo.setForeground(new java.awt.Color(0, 51, 255));

        fechaCampo.setEditable(false);
        fechaCampo.setForeground(new java.awt.Color(0, 51, 255));

        balanceCampo.setEditable(false);
        balanceCampo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        balanceCampo.setForeground(new java.awt.Color(0, 51, 255));

        cuentaDropDown.setForeground(new java.awt.Color(0, 51, 255));
        cuentaDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaDropDownActionPerformed(evt);
            }
        });

        depositarBtn.setForeground(new java.awt.Color(0, 51, 255));
        depositarBtn.setText("Depositar");
        depositarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarBtnActionPerformed(evt);
            }
        });

        extraerBtn.setForeground(new java.awt.Color(0, 51, 255));
        extraerBtn.setText("Extraer");
        extraerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraerBtnActionPerformed(evt);
            }
        });

        transferirBtn.setForeground(new java.awt.Color(0, 51, 255));
        transferirBtn.setText("Transferir");
        transferirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferirBtnActionPerformed(evt);
            }
        });

        salirBtn.setForeground(new java.awt.Color(0, 51, 255));
        salirBtn.setText("Salir");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("App Banca Online");

        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Autor: Derek Robert");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balanceCampo)
                            .addComponent(fechaCampo)
                            .addComponent(clienteCampo)
                            .addComponent(cuentaDropDown, 0, 159, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(depositarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transferirBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(extraerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salirBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(154, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cuentaDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositarBtn))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clienteCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extraerBtn))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fechaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferirBtn))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(balanceCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extraerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraerBtnActionPerformed
        String montoString = JOptionPane.showInputDialog(this, "Ingrese el monto a extraer: ", "Extraer", JOptionPane.PLAIN_MESSAGE);
        double monto = Double.parseDouble(montoString);
        actualCuenta.extraer(monto);
        balanceCampo.setText(String.valueOf(actualCuenta.getBalance()));    //resetear balance
        Utilidad.writeFile(cuentas, "cuentas.txt");
    }//GEN-LAST:event_extraerBtnActionPerformed

    private void cuentaDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaDropDownActionPerformed
        actualCuenta = (Cuenta) cuentaDropDown.getSelectedItem();       //Hice casting
        
        //Populamos GUI
        clienteCampo.setText(actualCuenta.getDuenioCuenta());
        fechaCampo.setText(actualCuenta.getFechaApertura());
        balanceCampo.setText(String.valueOf(actualCuenta.getBalance()));    //resetear balance
    }//GEN-LAST:event_cuentaDropDownActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void depositarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarBtnActionPerformed
        String montoString = JOptionPane.showInputDialog(this, "Ingrese el monto a depositar: ", "Depositar", JOptionPane.PLAIN_MESSAGE);
        double monto = Double.parseDouble(montoString);
        actualCuenta.depositar(monto);
        balanceCampo.setText(String.valueOf(actualCuenta.getBalance()));    //resetear balance
        Utilidad.writeFile(cuentas, "cuentas.txt");
    }//GEN-LAST:event_depositarBtnActionPerformed

    private void transferirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferirBtnActionPerformed

        String cuentaNumero = JOptionPane.showInputDialog(this, "Ingrese el numero de cuenta a transferir: ", "Transferir", JOptionPane.PLAIN_MESSAGE);
        Cuenta cuentaTransferida = null;
        for(Cuenta a: cuentas) {
            if(a.getNumeroCuenta().equals(cuentaNumero)) {         
                cuentaTransferida = a;
                break;
            }
        }
        String montoString = JOptionPane.showInputDialog(this, "Ingrese el monto a transferir: ", "Transferir", JOptionPane.PLAIN_MESSAGE);
        double monto = Double.parseDouble(montoString);
        if(cuentaTransferida != null) {
            actualCuenta.transferir(cuentaTransferida, monto);
            balanceCampo.setText(String.valueOf(actualCuenta.getBalance()));    //resetear balance
            Utilidad.writeFile(cuentas, "cuentas.txt");
        }   else {
            JOptionPane.showMessageDialog(null, "Numero de cuenta no existe en registro!");
        }
    }//GEN-LAST:event_transferirBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banco().setVisible(true);
            }
        });
        
        //Objeto Cuenta
        Cuenta acc = new Cuenta("999", "Derek", "1/1/2021", 1.00);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceCampo;
    private javax.swing.JTextField clienteCampo;
    private javax.swing.JComboBox<Cuenta> cuentaDropDown;
    private javax.swing.JButton depositarBtn;
    private javax.swing.JButton extraerBtn;
    private javax.swing.JTextField fechaCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton salirBtn;
    private javax.swing.JButton transferirBtn;
    // End of variables declaration//GEN-END:variables
}
